import { 
  Image, 
  Box, 
  Flex, 
  Text, 
  Heading 
} from '@chakra-ui/react'
import Head from 'next/head'
import list from './list'

const Intro = (props) => {
  return (
    <Box>
      <Heading color='red.500'>Hello, I'm Jerome</Heading>
      <Text fontSize='xl'>BS Computer Science Student</Text>
      <Text fontSize='sm'>University of Saint Louis - Tuguegarao</Text>
    </Box>
  );
}

export default function Home() {
  return (
    <Box>
      <Head>
        <title>Blog - Jerome</title>
        <meta name="Personal Blog Website" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex p={['10%','10%','8%','7%']} min-height='70%'>
        <Image
          boxSize={['290px', 'sm', 'sm', 'sm',]}
          justify={['center', 'center', 'flex-end', 'flex-end']}
          rounded='lg'
          Shadow='2xl'
          objectFit='cover'
          src='/Jerome.jpg'
          alt='Jerome Apalla'
          m='auto'
        />
      </Flex>
      <Intro name={list.name} />
    </Box>
  )
}
